### ISSUE TITLE
not loading in QGIS 2.6 from OSGeo4W 64bit installer

### ISSUE THREAD

**Issue by gubuntu** [kartoza/sg-diagram-downloader#29]
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 185, in loadPlugin
    __import__(packageName)
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/gavin/.qgis2/python/plugins\SGDiagramDownloader\__init__.py", line 41, in 
    custom_logging.setup_logger(SENTRY_URL)
  File "C:/Users/gavin/.qgis2/python/plugins\SGDiagramDownloader\custom_logging.py", line 169, in setup_logger
    client = Client(sentry_url)
  File "C:\Users\gavin\.qgis2\python\plugins\opengeo\ext-libs\raven-3.5.1-py2.7.egg\raven\base.py", line 183, in __init__
    context = {'sys.argv': sys.argv[:]}
AttributeError: 'module' object has no attribute 'argv'

**Comment by gubuntu** [comment]
redundant
