### ISSUE TITLE
Error loading plugin in QGIS 2.18.16 [Ubuntu Xenial]

### ISSUE THREAD

**Issue by Vince-Egan** [kartoza/sg-diagram-downloader#44]
Having trouble loading the plugin on Ubuntu Xenial QGIS v 2.18.16:
_______________________________
The plugin is broken. Python said:
unbound method __init__() must be called with Handler instance as first argument (got SentryHandler instance instead)
_______________________________

**Comment by NyakudyaA** [comment]
@ismailsunni  Plugin installs fine on Ubuntu 17.10 and QGIS 2.14.18 and QGIS 2.18.5.

**Comment by Gustry** [comment]
Maybe we should remove sentry?

**Comment by ismailsunni** [comment]
Hi @Vince-Egan 
Can you paste here the full stacktrace?
I don't have any Xenial here, but perhaps I will just remove the sentry like @Gustry's said. But it's quite strange since @NyakudyaA has it work....

@Vince-Egan Can you also uninstall and install it again? And try to restart QGIS...

**Comment by Gustry** [comment]
I guess this error is coming from the plugin manager, so it's only displaying the error that he posted here @ismailsunni . Maybe @Vince-Egan you have more info in the QGIS logs? ( the small bubble in the bottom right corner, check each tab)

**Comment by Vince-Egan** [comment]
Hi, sorry -was away from my computer.
Here is the response on the initial error:
___________________
Couldn't load plugin 'SGDiagramDownloader' 

TypeError: unbound method __init__() must be called with Handler instance as first argument (got SentryHandler instance instead) 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 308, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/vince/.qgis2/python/plugins/SGDiagramDownloader/__init__.py", line 41, in 
    custom_logging.setup_logger(SENTRY_URL)
  File "/home/vince/.qgis2/python/plugins/SGDiagramDownloader/custom_logging.py", line 169, in setup_logger
    sentry_handler = SentryHandler(client)
  File "/home/vince/.qgis2/python/plugins/StreamFeatureExtractor/third_party/raven/handlers/logging.py", line 43, in __init__
    logging.Handler.__init__(self, level=kwargs.get('level', logging.NOTSET))
TypeError: unbound method __init__() must be called with Handler instance as first argument (got SentryHandler instance instead)


Python version: 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609] 
QGIS version: 2.18.16 Las Palmas, d473c30 

Python Path:
/home/vince/.qgis2/python/plugins/UMEP/SUEWSPrepare/Modules
/home/vince/.qgis2/python/plugins/QMarxanToolbox
/home/vince/.qgis2/python/plugins/GeoCoding/libs
/usr/share/qgis/python/plugins/processing
/home/vince/.qgis2/python/plugins/pktools
/home/vince/.qgis2/python/plugins/UMEP/SUEWSPrepare/Modules
/home/vince/.qgis2/python/plugins/processing_workflow
/home/vince/.qgis2/python/plugins/ClusterPoints
/home/vince/.qgis2/python/plugins/LecoS
/usr/share/qgis/python
/home/vince/.qgis2/python
/home/vince/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/python2.7/dist-packages/wx-3.0-gtk2
/home/vince/.qgis2//python
/home/vince/.qgis2/python/plugins/gearthview/ext-libs
/home/vince/.qgis2/python/plugins/shpsync/xlwt-1.0.0-py2.7.egg
/home/vince/.qgis2/python/plugins/shpsync/xlrd-0.9.4-py2.7.egg
.
/home/vince/.qgis2/python/plugins/DigitizingTools/tools
/home/vince/.qgis2/python/plugins/qgis_resource_sharing
/home/vince/.qgis2/python/plugins/qgis_resource_sharing/ext_libs
/home/vince/.qgis2/python/plugins/FeatureGridCreator
/home/vince/.qgis2/python/plugins/StreamFeatureExtractor/third_party
/home/vince/.qgis2/python/plugins/MultiDistanceBuffer
/home/vince/.qgis2/python/plugins/mmqgis/forms
/home/vince/.qgis2/python/plugins
/home/vince/.qgis2/python/plugins
/home/vince/.qgis2/python/plugins/vrtbuilderplugin
/home/vince/.qgis2/python/plugins/cluz/forms
/home/vince/.qgis2/python/plugins/cluz/forms
/home/vince/.qgis2/python/plugins/MultiDistanceBuffer
/home/vince/.qgis2/python/plugins/SGDiagramDownloader/third_party
_________________________________________________
... and here are the logs, per tab:
GENERAL:
2018-02-14T07:47:15	0	QGIS starting...
2018-02-14T07:47:25	0	Python support ENABLED :-) 
2018-02-14T07:49:12	0	Application state:
			QGIS_PREFIX_PATH env var:		
			Prefix:		/usr
			Plugin Path:		/usr/lib/qgis/plugins
			Package Data Path:	/usr/share/qgis
			Active Theme Name:	default
			Active Theme Path:	/home/vince/.qgis2///themes/default/icons/
			Default Theme Path:	:/images/themes/default/
			SVG Search Paths:	/usr/share/qgis/svg/
					/home/vince/.qgis2//svg/
			User DB Path:	/usr/share/qgis/resources/qgis.db
			Auth DB Path:	/home/vince/.qgis2//qgis-auth.db
			
2018-02-14T07:49:12	0	QGIS Ready!

PYTHON WARNING:
2018-02-14T07:47:25	1	warning:/usr/lib/python2.7/dist-packages/osgeo/gdal.py:107: DeprecationWarning: gdalconst.py was placed in a namespace, it is now available as osgeo.gdalconst
			  DeprecationWarning)
			
			traceback:  File "<string>", line 1, in <module>
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python2.7/dist-packages/qgis/user.py", line 91, in <module>
			    expressions.load(expressionspath)
			  File "/usr/lib/python2.7/dist-packages/qgis/user.py", line 48, in load_user_expressions
			    __import__("expressions.{0}".format(name), locals(), globals())
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/home/vince/.qgis2/python/expressions/imagefootprint_exp.py", line 22, in <module>
			    from imagefootprint_plugin import CatalogFootprint
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/home/vince/.qgis2/python/plugins/imagefootprint_plugin/__init__.py", line 25, in <module>
			    from imagefootprint import ( DialogFootprint, CatalogFootprint )
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/home/vince/.qgis2/python/plugins/imagefootprint_plugin/imagefootprint.py", line 26, in <module>
			    from populatecatalog import PopulateCatalog, WorkerPopulateCatalog, Footprint
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/home/vince/.qgis2/python/plugins/imagefootprint_plugin/populatecatalog.py", line 29, in <module>
			    from gdalconst import GA_ReadOnly
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python2.7/dist-packages/gdalconst.py", line 3, in <module>
			    deprecation_warn('gdalconst')
			
2018-02-14T07:47:52	1	warning:/usr/lib/python2.7/dist-packages/matplotlib/__init__.py:1352: UserWarning:  This call to matplotlib.use() has no effect
			because the backend has already been chosen;
			matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
			or matplotlib.backends is imported for the first time.
			
			  warnings.warn(_use_error_msg)
			
			traceback:  File "<string>", line 1, in <module>
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "/home/vince/.qgis2/python/plugins/worldwidenight/__init__.py", line 34, in classFactory
			    from .worldwidenight import worldwidenight
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/home/vince/.qgis2/python/plugins/worldwidenight/worldwidenight.py", line 46, in <module>
			    from .daynight import DayNight
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/home/vince/.qgis2/python/plugins/worldwidenight/daynight.py", line 27, in <module>
			    matplotlib.use('Agg')
			
2018-02-14T07:48:04	1	warning:/home/vince/.qgis2/python/plugins/spline/splineplugin.py:41: DeprecationWarning: QgsMapCanvas.mapRenderer() is deprecated
			  self.mapRenderer = iface.mapCanvas().mapRenderer()
			
			traceback:  File "<string>", line 1, in <module>
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "/home/vince/.qgis2/python/plugins/spline/__init__.py", line 50, in classFactory
			    return SplinePlugin(iface)

PLUGINS:
2018-02-14T07:47:25	0	Loaded GPS Tools (Path: /usr/lib/qgis/plugins/libgpsimporterplugin.so)
2018-02-14T07:47:25	0	Loaded Heatmap (Path: /usr/lib/qgis/plugins/libheatmapplugin.so)
2018-02-14T07:47:25	0	Loaded Zonal statistics plugin (Path: /usr/lib/qgis/plugins/libzonalstatisticsplugin.so)
2018-02-14T07:47:41	0	Loaded Multiline Join (package: multilinejoin)
2018-02-14T07:47:42	0	Loaded Geospatial Simulation (package: geospatialsimulation)
2018-02-14T07:47:42	0	Loaded Pin Point (package: pinpoint)
2018-02-14T07:47:42	0	Loaded SRTM Downloader (package: SRTM-Downloader)
2018-02-14T07:47:43	0	Loaded D3 Data Visualization (package: d3datavis)
2018-02-14T07:47:44	0	Loaded Viewshed Analysis (package: ViewshedAnalysis)
2018-02-14T07:47:44	0	Loaded Plugin Reloader (package: plugin_reloader)
2018-02-14T07:47:45	0	Loaded Lat Lon Tools (package: latlontools)
2018-02-14T07:47:45	0	Loaded refFunctions (package: refFunctions)
2018-02-14T07:47:45	0	Loaded Qgis2threejs (package: Qgis2threejs)
2018-02-14T07:47:50	0	Loaded GEarthView (package: gearthview)
2018-02-14T07:47:50	0	Loaded SimpleSvg (package: simplesvg)
2018-02-14T07:47:51	0	Loaded LecoS - Landscape Ecology Statistics (package: LecoS)
2018-02-14T07:47:51	0	Loaded Point sampling tool (package: pointsamplingtool)
2018-02-14T07:47:52	0	Loaded ShpSync (package: shpsync)
2018-02-14T07:47:52	0	Loaded Natural Earth Raster (package: natural_earth_raster)
2018-02-14T07:47:52	0	Loaded Zoom to Point (package: zoomtopoint)
2018-02-14T07:47:52	0	Loaded OSMEditorRemoteControl (package: OSMEditorRemoteControl)
2018-02-14T07:47:52	0	Loaded Worldwide night (package: worldwidenight)
2018-02-14T07:47:54	0	Loaded Multitemporal Analyzer (package: multitemporalAnalizer)
2018-02-14T07:47:54	0	Loaded RasterStats (package: rasterstats)
2018-02-14T07:47:54	0	Loaded Profile tool (package: profiletool)
2018-02-14T07:47:55	0	Loaded RiverGIS (package: rivergis)
2018-02-14T07:47:55	0	Loaded MultiQml (package: multiqml)
2018-02-14T07:47:55	0	Loaded SLD4raster (package: SLD4raster)
2018-02-14T07:47:56	0	Loaded Locate points along lines (package: LocatePoints)
2018-02-14T07:47:56	0	Loaded GeoJSONPlugin (package: QgisGeoJSONExportPlugin)
2018-02-14T07:47:56	0	Loaded QNetwork (package: qnetwork)
2018-02-14T07:47:56	0	Loaded Contour plugin (package: contour)
2018-02-14T07:47:57	0	Loaded TimeManager (package: timemanager)
2018-02-14T07:47:58	0	Loaded Digitizing Tools (package: DigitizingTools)
2018-02-14T07:47:59	0	Loaded Swap Vector Direction (package: SwapVectorDirection)
2018-02-14T07:48:02	0	Loaded QGIS Resource Sharing (package: qgis_resource_sharing)
2018-02-14T07:48:03	0	Loaded Feature Grid Creator (package: FeatureGridCreator)
2018-02-14T07:48:03	0	Loaded RS&GIS (package: NITK_RS-GIS_17)
2018-02-14T07:48:03	0	Loaded QGISConefor (package: qgisconefor)
2018-02-14T07:48:03	0	Loaded ClusterPoints (package: ClusterPoints)
2018-02-14T07:48:04	0	Loaded Spline (package: spline)
2018-02-14T07:48:04	0	Loaded Mahalanobis Distance (package: MahalanobisDistance)
2018-02-14T07:48:04	0	Loaded SVG2ColoR (package: SVG2ColoR)
2018-02-14T07:48:05	0	Loaded Spreadsheet Layers (package: SpreadsheetLayers)
2018-02-14T07:48:05	0	Loaded Plugin Builder (package: pluginbuilder)
2018-02-14T07:48:05	0	Loaded Flow Trace (package: flowTrace)
2018-02-14T07:48:06	0	Loaded swath profile (package: swathProfile)
2018-02-14T07:48:06	0	Loaded Photo2Shape (package: photo2shape)
2018-02-14T07:48:06	0	Loaded Select by radius plus (package: qgis-select-by-radius-plus-plugin)
2018-02-14T07:48:07	0	Loaded Concave Hull (package: concavehull)
2018-02-14T07:48:07	0	Loaded Stream Feature Extractor (package: StreamFeatureExtractor)
2018-02-14T07:48:07	0	Loaded Buffer by Percentage (package: BufferByPercentage)
2018-02-14T07:48:08	0	Loaded Copy_Coords (package: copy_coords)
2018-02-14T07:48:08	0	Loaded QPackage (package: QPackage)
2018-02-14T07:48:08	0	Loaded Search Layers (package: searchlayers)
2018-02-14T07:48:08	0	Loaded Clusterpy - Spatially constrained clustering (package: clusterpy_qgis_plugin)
2018-02-14T07:48:08	0	Loaded Clipper (package: clipper)
2018-02-14T07:48:09	0	Loaded undoPropertiesChanges (package: undoPropertiesChanges)
2018-02-14T07:48:09	0	Loaded getWKT (package: getWKT)
2018-02-14T07:48:09	0	Loaded TomBio tools (package: TomBio)
2018-02-14T07:48:09	0	Loaded geoUmbriaSUIT (package: geoUmbriaSUIT)
2018-02-14T07:48:10	0	Loaded OpenLayers Plugin (package: openlayers_plugin)
2018-02-14T07:48:10	0	Loaded Multi-distance buffer (package: MultiDistanceBuffer)
2018-02-14T07:48:10	0	Loaded XyTools (package: xytools)
2018-02-14T07:48:10	0	Loaded OSMInfo (package: osminfo)
2018-02-14T07:48:10	0	Loaded Value Tool (package: valuetool)
2018-02-14T07:48:11	0	Loaded Clip Multiple Layers (package: ClipMultipleLayers)
2018-02-14T07:48:11	0	Loaded Processing Workflows (package: processing_workflow)
2018-02-14T07:48:12	0	Loaded mmqgis (package: mmqgis)
2018-02-14T07:48:12	0	Loaded Slicer (package: Slicer)
2018-02-14T07:48:12	0	Loaded Digitizr (package: digitizr)
2018-02-14T07:48:13	0	Loaded qgis2web (package: qgis2web)
2018-02-14T07:48:13	0	Loaded QuickWKT (package: QuickWKT)
2018-02-14T07:48:13	0	Loaded Rectangles Ovals Digitizing (package: rectovalDigit)
2018-02-14T07:48:13	0	Loaded spatialJoin (package: spatialJoin)
2018-02-14T07:48:14	0	Loaded ZoomToCoordinates (package: zoomtocoordinates)
2018-02-14T07:48:14	0	Loaded QChainage (package: qchainage)
2018-02-14T07:48:18	0	Loaded QuickMapServices (package: quick_map_services)
2018-02-14T07:48:18	0	Loaded realcentroid (package: realcentroid)
2018-02-14T07:48:18	0	Loaded QOSM (package: qosm)
2018-02-14T07:48:18	0	Loaded QTiles (package: qtiles)
2018-02-14T07:48:18	0	Loaded Multipart Split (package: splitmultipart)
2018-02-14T07:48:19	0	Loaded Report Plugin (package: report)
2018-02-14T07:48:19	0	Loaded OSMDownloader (package: OSMDownloader)
2018-02-14T07:48:19	0	Loaded Mask (package: mask)
2018-02-14T07:48:19	0	Loaded Statist (package: statist)
2018-02-14T07:48:24	0	Loaded Semi-Automatic Classification Plugin (package: SemiAutomaticClassificationPlugin)
2018-02-14T07:48:24	0	Loaded LayersByField (package: layers_by_field)
2018-02-14T07:48:24	0	Loaded Strahler (package: QGISStrahler-master)
2018-02-14T07:48:25	0	Loaded Turn Gray (package: TurnGray)
2018-02-14T07:48:25	0	Loaded Image Footprint (package: imagefootprint_plugin)
2018-02-14T07:48:25	0	Loaded Group Stats (package: GroupStats)
2018-02-14T07:48:25	0	Loaded MergeLines (package: QGISMergeLines-master)
2018-02-14T07:48:25	0	Loaded layer2kmz (package: layer2kmz)
2018-02-14T07:48:26	0	Loaded Transectizer (package: transectizer)
2018-02-14T07:48:26	0	Loaded Freehand raster georeferencer (package: FreehandRasterGeoreferencer)
2018-02-14T07:48:26	0	Loaded Shapefile Encoding Fixer (package: shapefile_encoding_fixer)
2018-02-14T07:48:26	0	Loaded qNote (package: qNote)
2018-02-14T07:48:26	0	Loaded Swap XY (package: swapXY)
2018-02-14T07:48:26	0	Loaded Raster Interpolation (package: rasterinterpolation)
2018-02-14T07:48:27	0	Loaded AutoTrace (package: autoTrace)
2018-02-14T07:48:29	0	Loaded QGIS Hats (package: qgis_hats)
2018-02-14T07:48:32	0	Loaded QuickOSM (package: QuickOSM)
2018-02-14T07:48:32	0	Loaded Multiple Layer Selection (package: MultipleLayerSelection)
2018-02-14T07:48:33	0	Loaded Easy AHP (package: EasyAHP)
2018-02-14T07:48:33	0	Loaded PosiView (package: PosiView)
2018-02-14T07:48:33	0	Loaded Metatools (package: metatools)
2018-02-14T07:48:34	0	Loaded GarminCustomMap (package: GarminCustomMap)
2018-02-14T07:48:34	0	Loaded Quick STEP (package: QuickSTEP)
2018-02-14T07:48:41	0	Loaded UMEP (package: UMEP)
2018-02-14T07:48:42	0	Loaded Area Along Vector (package: AreaAlongVector)
2018-02-14T07:48:42	0	Loaded WPS Client (package: wps)
2018-02-14T07:48:43	0	Loaded PCA (package: PrincipalComponents)
2018-02-14T07:48:43	0	Loaded Least-Cost-Paths Network (package: LCPNetwork)
2018-02-14T07:48:43	0	Loaded MOLUSCE (package: molusce)
2018-02-14T07:48:43	0	Loaded Join lines (package: joinlines)
2018-02-14T07:48:43	0	Loaded Raster Transparency (package: raster_transparency)
2018-02-14T07:48:44	0	Loaded pktools (package: pktools)
2018-02-14T07:48:44	0	Loaded Advanced Line Editor (package: ale)
2018-02-14T07:48:45	0	Loaded Virtual Raster Builder (package: vrtbuilderplugin)
2018-02-14T07:48:45	0	Loaded Temporal/Spectral Profile Tool (package: temporalprofiletool)
2018-02-14T07:48:45	0	Loaded Geometry Validator (package: GeometryValidator)
2018-02-14T07:48:45	0	Loaded Expressions Plus (package: qgsexpressionsplus)
2018-02-14T07:48:46	0	Loaded Send2GE (package: send2google_earth)
2018-02-14T07:48:46	0	Loaded Multi Ring Buffer (package: Multi_Ring_Buffer)
2018-02-14T07:48:46	0	Loaded Proportional circles (package: ProportionalCircles)
2018-02-14T07:48:46	0	Loaded Merge shapes (package: mergeshapes)
2018-02-14T07:48:47	0	Loaded versioning (package: qgis_versioning)
2018-02-14T07:48:47	0	Loaded Interactive Map Tracking (package: interactive_map_tracking)
2018-02-14T07:48:47	0	Loaded DB Manager (package: db_manager)
2018-02-14T07:48:57	0	Loaded Processing (package: processing)
2018-02-14T07:48:57	0	Loaded GdalTools (package: GdalTools)

TIMEMANAGER:
2018-02-14T07:47:57	0	Plugin language loaded: en
2018-02-14T07:47:57	0	Hello world!

PROCESSING:
2018-02-14T07:48:54	2	Problem with SAGA installation: SAGA was not found or is not correctly installed
2018-02-14T07:48:54	2	Could not load provider: 
			Traceback (most recent call last):
			  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 92, in addProvider
			    provider.initializeSettings()
			  File "/usr/share/qgis/python/plugins/processing/core/AlgorithmProvider.py", line 76, in initializeSettings
			    ProcessingConfig.settingIcons[self.getDescription()] = self.getIcon()
			  File "/home/vince/.qgis2/python/plugins/processing_workflow/WorkflowProviderBase.py", line 105, in getIcon
			    return QIcon(self.icon)
			AttributeError: 'WorkflowProviderBase' object has no attribute 'icon'

PYTHON ERROR:
2018-02-14T07:55:07	1	Traceback (most recent call last):
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 308, in loadPlugin
			    __import__(packageName)
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/home/vince/.qgis2/python/plugins/SGDiagramDownloader/__init__.py", line 41, in <module>
			    custom_logging.setup_logger(SENTRY_URL)
			  File "/home/vince/.qgis2/python/plugins/SGDiagramDownloader/custom_logging.py", line 169, in setup_logger
			    sentry_handler = SentryHandler(client)
			  File "/home/vince/.qgis2/python/plugins/StreamFeatureExtractor/third_party/raven/handlers/logging.py", line 43, in __init__
			    logging.Handler.__init__(self, level=kwargs.get('level', logging.NOTSET))
			TypeError: unbound method __init__() must be called with Handler instance as first argument (got SentryHandler instance instead)

**Comment by Vince-Egan** [comment]
Hi, plugin is now loading without any problem. Thanks!
