### ISSUE TITLE
Failure to install plugin 

### ISSUE THREAD

**Issue by Meyerdk** [kartoza/sg-diagram-downloader#54]
```
Couldn't load plugin 'SGDiagramDownloader' due to an error when calling its classFactory() method 

NameError: name 'Non' is not defined 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/meyer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SGDiagramDownloader\__init__.py", line 50, in classFactory
    from .plugin import SGDiagramDownloader
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/meyer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SGDiagramDownloader\plugin.py", line 46, in 
    from .sg_downloader import DownloadDialog
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/meyer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SGDiagramDownloader\sg_downloader.py", line 58, in 
    from .sg_utilities import download_sg_diagrams, write_log
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/meyer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SGDiagramDownloader\sg_utilities.py", line 67, in 
    from bs4 import BeautifulSoup
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\meyer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\SGDiagramDownloader\third_party\bs4\__init__.py", line 1, in 
    Non
NameError: name 'Non' is not defined


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.1-Firenze Firenze, fde3b8fbb8c 

Python Path:
C:/PROGRA~1/QGIS32~1.1/apps/qgis/./python
C:/Users/meyer/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/meyer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.1/apps/qgis/./python/plugins
C:\Users\meyer\OneDrive\Documents\tensorflow\models
C:\Users\meyer\OneDrive\Documents\tensorflow\models\research
C:\Users\meyer\OneDrive\Documents\tensorflow\models\research\slim
C:\Users\meyer\OneDrive\Documents\tensorflow\models\research\object_detection
C:\Users\meyer\PycharmProjects\object_detect
C:\Users\meyer\Documents
C:\Program Files\QGIS 3.28.1\bin\python39.zip
C:\PROGRA~1\QGIS32~1.1\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib
C:\Program Files\QGIS 3.28.1\bin
C:\PROGRA~1\QGIS32~1.1\apps\Python39
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\Pythonwin
C:/Users/meyer/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.
C:/Users/meyer/K2C/sample
C:\Users\meyer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\SGDiagramDownloader\third_party
```

**Comment by NyakudyaA** [comment]
```
Couldn't load plugin 'SGDiagramDownloader' 

RecursionError: maximum recursion depth exceeded 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/__init__.py", line 31, in 
    from . import custom_logging  # pylint: disable=relative-import
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/custom_logging.py", line 27, in 
    from raven.handlers.logging import SentryHandler  # noqa
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/third_party/raven/__init__.py", line 49, in 
    from raven.base import *  # NOQA
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/third_party/raven/base.py", line 37, in 
    from raven.conf.remote import RemoteConfig
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/third_party/raven/conf/remote.py", line 36, in 
    DEFAULT_TRANSPORT = discover_default_transport()
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/third_party/raven/conf/remote.py", line 18, in discover_default_transport
    from raven.transport.threaded import ThreadedHTTPTransport
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/third_party/raven/transport/__init__.py", line 17, in 
    from raven.transport.requests import *  # NOQA
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/third_party/raven/transport/requests.py", line 13, in 
    import requests
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 118, in 
    from . import utils
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 27, in 
    from ._internal_utils import to_native_string
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/requests/_internal_utils.py", line 11, in 
    from .compat import is_py2, builtin_str, str
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/requests/compat.py", line 29, in 
    import simplejson as json
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/third_party/simplejson/__init__.py", line 114, in 
    from .encoder import JSONEncoder, JSONEncoderForHTML
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/third_party/simplejson/encoder.py", line 39, in 
    ESCAPE_DCT.setdefault(chr(i), '\\u%04x' % (i,))
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/third_party/simplejson/compat.py", line 42, in chr
    return u(chr(s))
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/third_party/simplejson/compat.py", line 42, in chr
    return u(chr(s))
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/third_party/simplejson/compat.py", line 42, in chr
    return u(chr(s))
  [Previous line repeated 859 more times]
RecursionError: maximum recursion depth exceeded


Python version: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] 
QGIS version: 3.28.1-Firenze Firenze, 8b7e5769f0 

Python Path:
/usr/share/qgis/python
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/admire/.local/lib/python3.10/site-packages
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SGDiagramDownloader/third_party
```

**Comment by ismailsunni** [comment]
@NyakudyaA perhaps you need to update `simplejson` to the latest version. I check quickly, the `compat.py` no longer has that line of code. See: https://github.com/simplejson/simplejson/blob/master/simplejson/compat.py

**Comment by ismailsunni** [comment]
And this is obviouosly not good https://github.com/kartoza/sg-diagram-downloader/blob/develop/third_party/bs4/__init__.py#L1

**Comment by NyakudyaA** [comment]
When downloading the actual layers we encounter the following error
```
Downloading documents for C01300000000008600008 in Western Cape
Failed: Downloading SG code C01300000000008600008 for province Western Cape because of Failed to parse html page.
Downloading documents for C01300000000008600000 in Western Cape
Failed: Downloading SG code C01300000000008600000 for province Western Cape because of Failed to parse html page.
Downloading documents for C01300000000058200009 in Western Cape
Failed: Downloading SG code C01300000000058200009 for province Western Cape because of Failed to parse html page.
Downloading documents for C01300000000058200002 in Western Cape
Failed: Downloading SG code C01300000000058200002 for province Western Cape because of Failed to parse html page.
Downloading documents for C01300000000058200007 in Western Cape
Failed: Downloading SG code C01300000000058200007 for province Western Cape because of Failed to parse html page.
```

**Comment by NyakudyaA** [comment]
@Meyerdk You can try to update to a new plugin
